version: '3.5'

services:
    app:
        image: node:14
        volumes:
            - ./:/app
        working_dir: /app
        ports:
            - 3001:3000
        command: npm start
        tty: true
